services:
  - type: web
    name: glasgow-topographical-taxi-test
    runtime: static
    buildCommand: npm ci && npm run build
    staticPublishPath: ./dist
    envVars:
      - key: SKIP_INSTALL_DEPS
        value: "true"
      - key: VITE_BACKEND_BASE_URL
        value: "https://glasgow-topographical-taxi-osrm.onrender.com"
      - key: VITE_SUPABASE_URL
        sync: false
      - key: VITE_SUPABASE_PUBLISHABLE_KEY
        sync: false

  - type: web
    name: glasgow-topographical-taxi-osrm
    runtime: docker
    plan: free
    dockerfilePath: ./server/osrm/Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: PORT
        value: "10000"
